// <auto-generated />
namespace MotorcycleTW.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Change_MemberTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Change_MemberTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201908041701054_Change_MemberTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
